### PR TITLE
Add OpenRC support for ASUS Linux

### PR DESCRIPTION
**Pull request by xz-dev**
Tested

Refer: https://gitlab.com/asus-linux/asusctl/-/issues/59

### CODE REVIEW

**Comment by aspann** [comment]
Thanks for your contribution,
but as we can't merge on a mirror, I kindly ask you to close this PR.

I've added your scripts to the upcoming release (will be available in a moment).

**Comment by xz-dev** [comment]
You need to add `#!/sbin/openrc-run` at start in supergfxd.init and asusd.init

**Comment by aspann** [comment]
> You need to add `#!/sbin/openrc-run` at start in supergfxd.init and asusd.init

is that the correct shebang? (though `/sbin`  will be abandoned very soon)

**Comment by aspann** [comment]
nvm. so or so, I've just added it - should be available in a moment. Btw. it would be nice if you can ping me if there is a change, as I'm still not using OpenRC. ;-)

cheers.

**Comment by xz-dev** [comment]
> > You need to add `#!/sbin/openrc-run` at start in supergfxd.init and asusd.init
> 
> is that the correct shebang? (thought `/sbin` will be abandoned very soon)

I can confirmed every openrc script use /sbin/openrc-run

**Pull request closed without merging**
